name: Deploy Pages + Edge Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Installer Supabase CLI
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Injiser PROJECT_REF og EXPECTED_ADMIN_KEY i HTML
      - name: Inject placeholders
        shell: bash
        env:
          PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          EXPECTED_ADMIN_KEY: ${{ secrets.EXPECTED_ADMIN_KEY }}
        run: |
          set -euo pipefail
          esc(){ printf '%s' "$1" | sed -e 's/[\/&\\]/\\&/g'; }
          REF_ESC=$(esc "$PROJECT_REF")
          KEY_ESC=$(esc "$EXPECTED_ADMIN_KEY")
          for f in index.html admin.html; do
            [ -f "$f" ] || continue
            sed -i "s/__PROJECT_REF__/$REF_ESC/g" "$f"
            sed -i "s/__EXPECTED_ADMIN_KEY__/$KEY_ESC/g" "$f" || true
          done

      # Deploy Edge Functions (log + admin)
      - name: Supabase functions deploy
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"
          supabase functions deploy log --no-verify-jwt
          supabase functions deploy admin --no-verify-jwt


      # Publiser hele repoet som Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
